#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -Isrc -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -std=c++11 -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS) -lsfml-window -lsfml-graphics -lsfml-audio -lsfml-system
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/Engine

INC_RELEASE = $(INC) -Iinclude -Isrc
CFLAGS_RELEASE = $(CFLAGS) -O2 -std=c++11
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s -lsfml-window -lsfml-graphics -lsfml-audio -lsfml-system
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/Engine

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/Collision.o $(OBJDIR_DEBUG)/src/Config.o $(OBJDIR_DEBUG)/src/Game.o $(OBJDIR_DEBUG)/src/Main.o $(OBJDIR_DEBUG)/src/MenuState.o $(OBJDIR_DEBUG)/src/RandomValues.o $(OBJDIR_DEBUG)/src/State.o $(OBJDIR_DEBUG)/src/StateManager.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/Collision.o $(OBJDIR_RELEASE)/src/Config.o $(OBJDIR_RELEASE)/src/Game.o $(OBJDIR_RELEASE)/src/Main.o $(OBJDIR_RELEASE)/src/MenuState.o $(OBJDIR_RELEASE)/src/RandomValues.o $(OBJDIR_RELEASE)/src/State.o $(OBJDIR_RELEASE)/src/StateManager.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/Collision.o: src/Collision.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Collision.cpp -o $(OBJDIR_DEBUG)/src/Collision.o

$(OBJDIR_DEBUG)/src/Config.o: src/Config.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Config.cpp -o $(OBJDIR_DEBUG)/src/Config.o

$(OBJDIR_DEBUG)/src/Game.o: src/Game.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Game.cpp -o $(OBJDIR_DEBUG)/src/Game.o

$(OBJDIR_DEBUG)/src/Main.o: src/Main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/Main.cpp -o $(OBJDIR_DEBUG)/src/Main.o

$(OBJDIR_DEBUG)/src/MenuState.o: src/MenuState.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/MenuState.cpp -o $(OBJDIR_DEBUG)/src/MenuState.o

$(OBJDIR_DEBUG)/src/RandomValues.o: src/RandomValues.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/RandomValues.cpp -o $(OBJDIR_DEBUG)/src/RandomValues.o

$(OBJDIR_DEBUG)/src/State.o: src/State.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/State.cpp -o $(OBJDIR_DEBUG)/src/State.o

$(OBJDIR_DEBUG)/src/StateManager.o: src/StateManager.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/StateManager.cpp -o $(OBJDIR_DEBUG)/src/StateManager.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/Collision.o: src/Collision.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Collision.cpp -o $(OBJDIR_RELEASE)/src/Collision.o

$(OBJDIR_RELEASE)/src/Config.o: src/Config.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Config.cpp -o $(OBJDIR_RELEASE)/src/Config.o

$(OBJDIR_RELEASE)/src/Game.o: src/Game.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Game.cpp -o $(OBJDIR_RELEASE)/src/Game.o

$(OBJDIR_RELEASE)/src/Main.o: src/Main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/Main.cpp -o $(OBJDIR_RELEASE)/src/Main.o

$(OBJDIR_RELEASE)/src/MenuState.o: src/MenuState.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/MenuState.cpp -o $(OBJDIR_RELEASE)/src/MenuState.o

$(OBJDIR_RELEASE)/src/RandomValues.o: src/RandomValues.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/RandomValues.cpp -o $(OBJDIR_RELEASE)/src/RandomValues.o

$(OBJDIR_RELEASE)/src/State.o: src/State.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/State.cpp -o $(OBJDIR_RELEASE)/src/State.o

$(OBJDIR_RELEASE)/src/StateManager.o: src/StateManager.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/StateManager.cpp -o $(OBJDIR_RELEASE)/src/StateManager.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

